package net.pupp.musicdiscsplus.items;

import cpw.mods.util.Lazy;
import net.minecraft.client.resources.sounds.Sound;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.packs.resources.Resource;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import net.pupp.musicdiscsplus.MusicDiscsPlus;

public final class SoundInit {

    public static final DeferredRegister<SoundEvent> DISC_SOUNDS = DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, MusicDiscsPlus.MOD_ID);

    public static final RegistryObject<SoundEvent> DISC_001 = DISC_SOUNDS.register("music.disc_001", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_001")));
    public static final RegistryObject<SoundEvent> DISC_002 = DISC_SOUNDS.register("music.disc_002", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_002")));
    public static final RegistryObject<SoundEvent> DISC_003 = DISC_SOUNDS.register("music.disc_003", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_003")));
    public static final RegistryObject<SoundEvent> DISC_004 = DISC_SOUNDS.register("music.disc_004", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_004")));
    public static final RegistryObject<SoundEvent> DISC_005 = DISC_SOUNDS.register("music.disc_005", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_005")));
    public static final RegistryObject<SoundEvent> DISC_006 = DISC_SOUNDS.register("music.disc_006", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_006")));
    public static final RegistryObject<SoundEvent> DISC_007 = DISC_SOUNDS.register("music.disc_007", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_007")));
    public static final RegistryObject<SoundEvent> DISC_008 = DISC_SOUNDS.register("music.disc_008", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_008")));
    public static final RegistryObject<SoundEvent> DISC_009 = DISC_SOUNDS.register("music.disc_009", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_009")));
    public static final RegistryObject<SoundEvent> DISC_010 = DISC_SOUNDS.register("music.disc_010", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_010")));
    public static final RegistryObject<SoundEvent> DISC_011 = DISC_SOUNDS.register("music.disc_011", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_011")));
    public static final RegistryObject<SoundEvent> DISC_012 = DISC_SOUNDS.register("music.disc_012", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_012")));
    public static final RegistryObject<SoundEvent> DISC_013 = DISC_SOUNDS.register("music.disc_013", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_013")));
    public static final RegistryObject<SoundEvent> DISC_014 = DISC_SOUNDS.register("music.disc_014", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_014")));
    public static final RegistryObject<SoundEvent> DISC_015 = DISC_SOUNDS.register("music.disc_015", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_015")));
    public static final RegistryObject<SoundEvent> DISC_016 = DISC_SOUNDS.register("music.disc_016", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_016")));
    public static final RegistryObject<SoundEvent> DISC_017 = DISC_SOUNDS.register("music.disc_017", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_017")));
    public static final RegistryObject<SoundEvent> DISC_018 = DISC_SOUNDS.register("music.disc_018", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_018")));
    public static final RegistryObject<SoundEvent> DISC_019 = DISC_SOUNDS.register("music.disc_019", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_019")));
    public static final RegistryObject<SoundEvent> DISC_020 = DISC_SOUNDS.register("music.disc_020", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_020")));
    public static final RegistryObject<SoundEvent> DISC_021 = DISC_SOUNDS.register("music.disc_021", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_021")));
    public static final RegistryObject<SoundEvent> DISC_022 = DISC_SOUNDS.register("music.disc_022", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_022")));
    public static final RegistryObject<SoundEvent> DISC_023 = DISC_SOUNDS.register("music.disc_023", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_023")));
    public static final RegistryObject<SoundEvent> DISC_024 = DISC_SOUNDS.register("music.disc_024", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_024")));
    public static final RegistryObject<SoundEvent> DISC_025 = DISC_SOUNDS.register("music.disc_025", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_025")));
    public static final RegistryObject<SoundEvent> DISC_026 = DISC_SOUNDS.register("music.disc_026", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_026")));
    public static final RegistryObject<SoundEvent> DISC_027 = DISC_SOUNDS.register("music.disc_027", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_027")));
    public static final RegistryObject<SoundEvent> DISC_028 = DISC_SOUNDS.register("music.disc_028", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_028")));
    public static final RegistryObject<SoundEvent> DISC_029 = DISC_SOUNDS.register("music.disc_029", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_029")));
    public static final RegistryObject<SoundEvent> DISC_030 = DISC_SOUNDS.register("music.disc_030", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_030")));
    public static final RegistryObject<SoundEvent> DISC_031 = DISC_SOUNDS.register("music.disc_031", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_031")));
    public static final RegistryObject<SoundEvent> DISC_032 = DISC_SOUNDS.register("music.disc_032", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_032")));
    public static final RegistryObject<SoundEvent> DISC_033 = DISC_SOUNDS.register("music.disc_033", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_033")));
    public static final RegistryObject<SoundEvent> DISC_034 = DISC_SOUNDS.register("music.disc_034", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_034")));
    public static final RegistryObject<SoundEvent> DISC_035 = DISC_SOUNDS.register("music.disc_035", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_035")));
    public static final RegistryObject<SoundEvent> DISC_036 = DISC_SOUNDS.register("music.disc_036", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_036")));
    public static final RegistryObject<SoundEvent> DISC_037 = DISC_SOUNDS.register("music.disc_037", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_037")));
    public static final RegistryObject<SoundEvent> DISC_038 = DISC_SOUNDS.register("music.disc_038", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_038")));
    public static final RegistryObject<SoundEvent> DISC_039 = DISC_SOUNDS.register("music.disc_039", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_039")));
    public static final RegistryObject<SoundEvent> DISC_040 = DISC_SOUNDS.register("music.disc_040", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_040")));
    public static final RegistryObject<SoundEvent> DISC_041 = DISC_SOUNDS.register("music.disc_041", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_041")));
    public static final RegistryObject<SoundEvent> DISC_042 = DISC_SOUNDS.register("music.disc_042", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_042")));
    public static final RegistryObject<SoundEvent> DISC_043 = DISC_SOUNDS.register("music.disc_043", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_043")));
    public static final RegistryObject<SoundEvent> DISC_044 = DISC_SOUNDS.register("music.disc_044", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_044")));
    public static final RegistryObject<SoundEvent> DISC_045 = DISC_SOUNDS.register("music.disc_045", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_045")));
    public static final RegistryObject<SoundEvent> DISC_046 = DISC_SOUNDS.register("music.disc_046", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_046")));
    public static final RegistryObject<SoundEvent> DISC_047 = DISC_SOUNDS.register("music.disc_047", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_047")));
    public static final RegistryObject<SoundEvent> DISC_048 = DISC_SOUNDS.register("music.disc_048", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_048")));
    public static final RegistryObject<SoundEvent> DISC_049 = DISC_SOUNDS.register("music.disc_049", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_049")));
    public static final RegistryObject<SoundEvent> DISC_050 = DISC_SOUNDS.register("music.disc_050", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_050")));
    public static final RegistryObject<SoundEvent> DISC_051 = DISC_SOUNDS.register("music.disc_051", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_051")));
    public static final RegistryObject<SoundEvent> DISC_052 = DISC_SOUNDS.register("music.disc_052", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_052")));
    public static final RegistryObject<SoundEvent> DISC_053 = DISC_SOUNDS.register("music.disc_053", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_053")));
    public static final RegistryObject<SoundEvent> DISC_054 = DISC_SOUNDS.register("music.disc_054", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_054")));
    public static final RegistryObject<SoundEvent> DISC_055 = DISC_SOUNDS.register("music.disc_055", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_055")));
    public static final RegistryObject<SoundEvent> DISC_056 = DISC_SOUNDS.register("music.disc_056", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_056")));
    public static final RegistryObject<SoundEvent> DISC_057 = DISC_SOUNDS.register("music.disc_057", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_057")));
    public static final RegistryObject<SoundEvent> DISC_058 = DISC_SOUNDS.register("music.disc_058", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_058")));
    public static final RegistryObject<SoundEvent> DISC_059 = DISC_SOUNDS.register("music.disc_059", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_059")));
    public static final RegistryObject<SoundEvent> DISC_060 = DISC_SOUNDS.register("music.disc_060", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_060")));
    public static final RegistryObject<SoundEvent> DISC_061 = DISC_SOUNDS.register("music.disc_061", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_061")));
    public static final RegistryObject<SoundEvent> DISC_062 = DISC_SOUNDS.register("music.disc_062", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_062")));
    public static final RegistryObject<SoundEvent> DISC_063 = DISC_SOUNDS.register("music.disc_063", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_063")));
    public static final RegistryObject<SoundEvent> DISC_064 = DISC_SOUNDS.register("music.disc_064", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_064")));
    public static final RegistryObject<SoundEvent> DISC_065 = DISC_SOUNDS.register("music.disc_065", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_065")));
    public static final RegistryObject<SoundEvent> DISC_066 = DISC_SOUNDS.register("music.disc_066", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_066")));
    public static final RegistryObject<SoundEvent> DISC_067 = DISC_SOUNDS.register("music.disc_067", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_067")));
    public static final RegistryObject<SoundEvent> DISC_068 = DISC_SOUNDS.register("music.disc_068", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_068")));
    public static final RegistryObject<SoundEvent> DISC_069 = DISC_SOUNDS.register("music.disc_069", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_069")));
    public static final RegistryObject<SoundEvent> DISC_070 = DISC_SOUNDS.register("music.disc_070", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_070")));
    public static final RegistryObject<SoundEvent> DISC_071 = DISC_SOUNDS.register("music.disc_071", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_071")));
    public static final RegistryObject<SoundEvent> DISC_072 = DISC_SOUNDS.register("music.disc_072", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_072")));
    public static final RegistryObject<SoundEvent> DISC_073 = DISC_SOUNDS.register("music.disc_073", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_073")));
    public static final RegistryObject<SoundEvent> DISC_074 = DISC_SOUNDS.register("music.disc_074", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_074")));
    public static final RegistryObject<SoundEvent> DISC_075 = DISC_SOUNDS.register("music.disc_075", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_075")));
    public static final RegistryObject<SoundEvent> DISC_076 = DISC_SOUNDS.register("music.disc_076", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_076")));
    public static final RegistryObject<SoundEvent> DISC_077 = DISC_SOUNDS.register("music.disc_077", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_077")));
    public static final RegistryObject<SoundEvent> DISC_078 = DISC_SOUNDS.register("music.disc_078", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_078")));
    public static final RegistryObject<SoundEvent> DISC_079 = DISC_SOUNDS.register("music.disc_079", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_079")));
    public static final RegistryObject<SoundEvent> DISC_080 = DISC_SOUNDS.register("music.disc_080", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_080")));
    public static final RegistryObject<SoundEvent> DISC_081 = DISC_SOUNDS.register("music.disc_081", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_081")));
    public static final RegistryObject<SoundEvent> DISC_082 = DISC_SOUNDS.register("music.disc_082", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_082")));
    public static final RegistryObject<SoundEvent> DISC_083 = DISC_SOUNDS.register("music.disc_083", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_083")));
    public static final RegistryObject<SoundEvent> DISC_084 = DISC_SOUNDS.register("music.disc_084", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_084")));
    public static final RegistryObject<SoundEvent> DISC_085 = DISC_SOUNDS.register("music.disc_085", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_085")));
    public static final RegistryObject<SoundEvent> DISC_086 = DISC_SOUNDS.register("music.disc_086", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_086")));
    public static final RegistryObject<SoundEvent> DISC_087 = DISC_SOUNDS.register("music.disc_087", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_087")));
    public static final RegistryObject<SoundEvent> DISC_088 = DISC_SOUNDS.register("music.disc_088", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_088")));
    public static final RegistryObject<SoundEvent> DISC_089 = DISC_SOUNDS.register("music.disc_089", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_089")));
    public static final RegistryObject<SoundEvent> DISC_090 = DISC_SOUNDS.register("music.disc_090", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_090")));
    public static final RegistryObject<SoundEvent> DISC_091 = DISC_SOUNDS.register("music.disc_091", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_091")));
    public static final RegistryObject<SoundEvent> DISC_092 = DISC_SOUNDS.register("music.disc_092", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_092")));
    public static final RegistryObject<SoundEvent> DISC_093 = DISC_SOUNDS.register("music.disc_093", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_093")));
    public static final RegistryObject<SoundEvent> DISC_094 = DISC_SOUNDS.register("music.disc_094", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_094")));
    public static final RegistryObject<SoundEvent> DISC_095 = DISC_SOUNDS.register("music.disc_095", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_095")));
    public static final RegistryObject<SoundEvent> DISC_096 = DISC_SOUNDS.register("music.disc_096", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_096")));
    public static final RegistryObject<SoundEvent> DISC_097 = DISC_SOUNDS.register("music.disc_097", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_097")));
    public static final RegistryObject<SoundEvent> DISC_098 = DISC_SOUNDS.register("music.disc_098", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_098")));
    public static final RegistryObject<SoundEvent> DISC_099 = DISC_SOUNDS.register("music.disc_099", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_099")));
    public static final RegistryObject<SoundEvent> DISC_100 = DISC_SOUNDS.register("music.disc_100", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_100")));
    public static final RegistryObject<SoundEvent> DISC_101 = DISC_SOUNDS.register("music.disc_101", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_101")));
    public static final RegistryObject<SoundEvent> DISC_102 = DISC_SOUNDS.register("music.disc_102", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_102")));
    public static final RegistryObject<SoundEvent> DISC_103 = DISC_SOUNDS.register("music.disc_103", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_103")));
    public static final RegistryObject<SoundEvent> DISC_104 = DISC_SOUNDS.register("music.disc_104", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_104")));
    public static final RegistryObject<SoundEvent> DISC_105 = DISC_SOUNDS.register("music.disc_105", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_105")));
    public static final RegistryObject<SoundEvent> DISC_106 = DISC_SOUNDS.register("music.disc_106", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_106")));
    public static final RegistryObject<SoundEvent> DISC_107 = DISC_SOUNDS.register("music.disc_107", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_107")));
    public static final RegistryObject<SoundEvent> DISC_108 = DISC_SOUNDS.register("music.disc_108", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_108")));
    public static final RegistryObject<SoundEvent> DISC_109 = DISC_SOUNDS.register("music.disc_109", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_109")));
    public static final RegistryObject<SoundEvent> DISC_110 = DISC_SOUNDS.register("music.disc_110", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_110")));
    public static final RegistryObject<SoundEvent> DISC_111 = DISC_SOUNDS.register("music.disc_111", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_111")));
    public static final RegistryObject<SoundEvent> DISC_112 = DISC_SOUNDS.register("music.disc_112", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_112")));
    public static final RegistryObject<SoundEvent> DISC_113 = DISC_SOUNDS.register("music.disc_113", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_113")));
    public static final RegistryObject<SoundEvent> DISC_114 = DISC_SOUNDS.register("music.disc_114", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_114")));
    public static final RegistryObject<SoundEvent> DISC_115 = DISC_SOUNDS.register("music.disc_115", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_115")));
    public static final RegistryObject<SoundEvent> DISC_116 = DISC_SOUNDS.register("music.disc_116", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_116")));
    public static final RegistryObject<SoundEvent> DISC_117 = DISC_SOUNDS.register("music.disc_117", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_117")));
    public static final RegistryObject<SoundEvent> DISC_118 = DISC_SOUNDS.register("music.disc_118", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_118")));
    public static final RegistryObject<SoundEvent> DISC_119 = DISC_SOUNDS.register("music.disc_119", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_119")));
    public static final RegistryObject<SoundEvent> DISC_120 = DISC_SOUNDS.register("music.disc_120", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_120")));
    public static final RegistryObject<SoundEvent> DISC_121 = DISC_SOUNDS.register("music.disc_121", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_121")));
    public static final RegistryObject<SoundEvent> DISC_122 = DISC_SOUNDS.register("music.disc_122", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_122")));
    public static final RegistryObject<SoundEvent> DISC_123 = DISC_SOUNDS.register("music.disc_123", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_123")));
    public static final RegistryObject<SoundEvent> DISC_124 = DISC_SOUNDS.register("music.disc_124", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_124")));
    public static final RegistryObject<SoundEvent> DISC_125 = DISC_SOUNDS.register("music.disc_125", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_125")));
    public static final RegistryObject<SoundEvent> DISC_126 = DISC_SOUNDS.register("music.disc_126", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_126")));
    public static final RegistryObject<SoundEvent> DISC_127 = DISC_SOUNDS.register("music.disc_127", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_127")));
    public static final RegistryObject<SoundEvent> DISC_128 = DISC_SOUNDS.register("music.disc_128", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_128")));
    public static final RegistryObject<SoundEvent> DISC_129 = DISC_SOUNDS.register("music.disc_129", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_129")));
    public static final RegistryObject<SoundEvent> DISC_130 = DISC_SOUNDS.register("music.disc_130", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_130")));
    public static final RegistryObject<SoundEvent> DISC_131 = DISC_SOUNDS.register("music.disc_131", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_131")));
    public static final RegistryObject<SoundEvent> DISC_132 = DISC_SOUNDS.register("music.disc_132", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_132")));
    public static final RegistryObject<SoundEvent> DISC_133 = DISC_SOUNDS.register("music.disc_133", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_133")));
    public static final RegistryObject<SoundEvent> DISC_134 = DISC_SOUNDS.register("music.disc_134", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_134")));
    public static final RegistryObject<SoundEvent> DISC_135 = DISC_SOUNDS.register("music.disc_135", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_135")));
    public static final RegistryObject<SoundEvent> DISC_136 = DISC_SOUNDS.register("music.disc_136", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_136")));
    public static final RegistryObject<SoundEvent> DISC_137 = DISC_SOUNDS.register("music.disc_137", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_137")));
    public static final RegistryObject<SoundEvent> DISC_138 = DISC_SOUNDS.register("music.disc_138", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_138")));
    public static final RegistryObject<SoundEvent> DISC_139 = DISC_SOUNDS.register("music.disc_139", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_139")));
    public static final RegistryObject<SoundEvent> DISC_140 = DISC_SOUNDS.register("music.disc_140", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_140")));
    public static final RegistryObject<SoundEvent> DISC_141 = DISC_SOUNDS.register("music.disc_141", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_141")));
    public static final RegistryObject<SoundEvent> DISC_142 = DISC_SOUNDS.register("music.disc_142", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_142")));
    public static final RegistryObject<SoundEvent> DISC_143 = DISC_SOUNDS.register("music.disc_143", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_143")));
    public static final RegistryObject<SoundEvent> DISC_144 = DISC_SOUNDS.register("music.disc_144", () -> new SoundEvent(new ResourceLocation(MusicDiscsPlus.MOD_ID, "music.disc_144")));

    private SoundInit() {

    }
}
